package routes

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"path/filepath"

	"github.com/gin-gonic/gin"
	"github.com/jackc/pgx/v4"
)

func createByteArr(c *gin.Context, file *multipart.FileHeader) (*bytes.Buffer, error) {
	src, err := file.Open()
	if err != nil {
		return nil, err
	}

	defer src.Close()

	buf := bytes.NewBuffer(nil)

	if _, err := io.Copy(buf, src); err != nil {
		return nil, errors.New("Not all file bytes could be read.")
	}

	if buf.Len() != int(file.Size) {
		return nil, errors.New("Not all file bytes could be read.")
	}

	return buf, nil
}

func UploadHandler(db *pgx.Conn) gin.HandlerFunc {
	fn := func(c *gin.Context) {
		file, err := c.FormFile("uploadedFile")

		if err != nil {
			c.String(400, err.Error())
			return
		}

		buffer, err := createByteArr(c, file)

		if err != nil {
			c.String(400, err.Error())
		}

		tx, err := db.Begin(context.Background())

		if err != nil {
			fmt.Println(err.Error())
			c.String(400, err.Error())
			return
		}

		createQuery := `
			create table if not exists files(
				id integer generated by default as identity primary key,
				pid integer references files default null,
				loid integer,
				uploaded_at timestamp with time zone default now(),
				name text,
				file_type text,
				size int
			)
		`

		if _, err := tx.Exec(context.Background(), createQuery); err != nil {
			fmt.Println(err.Error())
			c.String(400, "failed to create files table.")
			return
		}

		lo := tx.LargeObjects()

		loid, err := lo.Create(context.Background(), 0)
		if err != nil {
			c.String(400, "failed to create object.")
			return
		}

		obj, err := lo.Open(context.Background(), loid, pgx.LargeObjectModeWrite)
		if err != nil {
			c.String(400, "failed to open object.")
			return
		}

		n, err := obj.Write(buffer.Bytes())
		if err != nil {
			c.String(400, "failed to write object.")
			return
		}

		if n != int(file.Size) {
			c.String(400, "Expected n to be %d, got %d", int(file.Size), n)
			return
		}

		if err := tx.Commit(context.Background()); err != nil {
			c.String(400, "failed to write object.")
			return
		}

		insertQuery := `
			insert into
			files(loid, file_type, name, size)
			values($1, $2, $3, $4)
		`

		ext := filepath.Ext(file.Filename)

		if _, err := db.Exec(context.Background(),
			insertQuery,
			loid,
			ext,
			file.Filename,
			file.Size); err != nil {
			fmt.Println(err.Error())
		}

		c.String(200, "success")
		return
	}

	return gin.HandlerFunc(fn)
}
